// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AuthenticationContext))]
    [Migration("20230624103737_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.TblAircrafts", b =>
                {
                    b.Property<string>("AircraftCode")
                        .HasColumnType("text");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AircraftCode");

                    b.ToTable("tblAircrafts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TblBookings", b =>
                {
                    b.Property<string>("AircraftCode")
                        .HasColumnType("text");

                    b.Property<string>("SeatNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AircraftCode");

                    b.ToTable("tblBookings", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TblUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("UsrEmail")
                        .HasColumnType("text");

                    b.Property<string>("UsrPassword")
                        .HasColumnType("text");

                    b.Property<string>("UsrPhoneNo")
                        .HasColumnType("text");

                    b.Property<string>("UsrRole")
                        .HasColumnType("text");

                    b.HasKey("UserName");

                    b.ToTable("tblUsers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
